import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/src/app/Context/ThemeContext";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todo List App",
  description: "Generated by Tanmay Kothari",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2563eb" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <Toaster /> {/* Toast container */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
